### ISSUE TITLE
Treat note on with velocity 0 as note off

### ISSUE THREAD

**Issue by feeling001** [moddevices/mod-ttymidi#1]
Hello, 

I use your ttymidi on my raspberry pi 3 (uart0 set at midi baudrate).
It works successfully , but "notes off" didn't work with my midi keyboard. 
After some investigation, my midi keyboard (Roland A33) sent "note on with velocity 0" as note off 

https://www.kvraudio.com/forum/viewtopic.php?t=291892

Apparently, this is a normal behavior. So is it possible to handle this type of message in ttymidi ?

I Used this small python script to debug.

import serial
ser = serial.Serial('/dev/serial0', baudrate=38400)
while True:
  i = 0
  data = ord(ser.read(1))
  print "m= " + "{0:b}".format(data)

Regards,
Laurent.

**Comment by falkTX** [comment]
I do not agree with the proposed change.
MIDI keyboards sending note-off as note-on with zero velocity is a common feature.

If we do this change in ttymidi, we're changing how a device works in serial-midi vs midi-usb.

You need to have your client software handle such events.
