### ISSUE TITLE
Does ttymidi support Midi clock (Start, stop, clock) ?

### ISSUE THREAD

**Issue by nordseele** [moddevices/mod-ttymidi#16]
Hi, 

I'm trying to send some single byte messages  like Start, Stop, Clock (respectively 250, 252, 248) but they are not sent.
According to the documentation,  "ttymidi forces every command into 3 bytes", so I tried to complete the array with zeros (ie: [250, 0, 0] ) but I only receive a "MidiOutAlsa::sendMessage: event parsing error" when i do.

Does ttymidi support Midi clock (Start, stop, clock) ?

Thanks.

**Comment by falkTX** [comment]
Not sure if you got the right project..

This is a fork of ttymidi which deals with JACK, there is nothing for ALSA here.
(if there is, it will be some legacy stuff that should to be deleted)

MIDI time / MMC works, it is used in MOD Devices.

**Comment by nordseele** [comment]
Ah yes, my bad. And reading the code yes it should support clocks. sorry :-)
