### ISSUE TITLE
please help make setup tty instructions more clear?

### ISSUE THREAD

**Issue by jayknowstheway** [moddevices/mod-ttymidi#3]
Hello and thank you for building an awesome tool! However, it's taken me many hours and I still don't get how to use this with arduino.

[This](
https://www.partsnotincluded.com/arduino/how-to-control-anything-on-arduino-using-midi) was the tutorial I was trying to follow, but hairless doesn't work on linux as far as I've tried. So tty was the solution, sadly there's nothing very clear and straightforward to explain how to use it. First, finding out what serial was being used by my arduino was a nightmare search:
ls -l /dev/serial/by-id/

Connecting to it seems straightforward: ttymidi -s /dev/ttyACM0 -v
However, when I run the example code, it says device is busy and it won't connect to it.

Also, the MIDI_Basic_IO_ttymidi.pde has a bug, which I managed to get past by including:
 // Created and binds the MIDI interface to the default hardware Serial port
 MIDI_CREATE_DEFAULT_INSTANCE();
The other tutorials really don't show anything else besides tutorial code, which while useful, doesn't really address the whole setup thing..

My question is, how do I get my midi keyboard to respond via tty to control arduino successfully? And through that, could you help update the documentation or examples to be comprehensive in walking someone through that, almost as if they were a kindergartner? Ladyada's website is a great example of that. Thank you!

**Comment by jkbd** [comment]
Hi @jayknowstheway,
I'm not sure, this project fits your goals. You can run ttymidi on a Linux machine to parse MIDI events from a serial line. You could ground the reset pin of a Arduino to use it as a USB-to-Serial-Port adapter with your computer. The code in this repository is _not_ meant to run standalone on an Arduino.

**Comment by jkbd** [comment]
You're welcome! As I understand you this is not an issue and I close this now.
