### ISSUE TITLE
error opening / creating jack client

### ISSUE THREAD

**Issue by luatlu** [moddevices/mod-ttymidi#4]
Hello,

I try to use the Arduino Uno to send midi messages via usb. I installed ttymidi and libjack-jackd2-dev as written in the readme and also build-essential (for compiling ttymidi) & qjackctl. (on Linux Mint 19 Tara)

Now the command

`sudo ttymidi -s /dev/ttyACM0 -v`

results in

> Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Error opening JACK client.
Error creating jack client.

Do you have any hints to solve this?
Thank You in Advance

**Comment by jkbd** [comment]
This is not an issue with ttymidi.
Please read again this error message:
> jack server is not running or cannot be started
Ttymidi is a jack client, so you need to have a jack server running beforehand.

**Comment by luatlu** [comment]
Of course i first opened up qjackctl and pressed start. Is this what you mean?

**Comment by luatlu** [comment]
For all newbies like me who got stuck at the same point. 

`sudo chmod a+rw /dev/ttyACM0`

was what I needed.
