### ISSUE TITLE
Support MIDI running status

### ISSUE THREAD

**Issue by Baggypants** [moddevices/mod-ttymidi#7]
I have a board that makes using ttyMIDI problematic as it uses running status.

It is an evolution MK-449C. A zynthian user has reported the Yamaha CS1x has the same issue.

**Comment by Baggypants** [comment]
Also a Yamaha DJX

**Comment by falkTX** [comment]
getting our hands in one of these is not very practical.
are you able to record a MIDI file with the data that these keyboards send?

I will then be able to replicate the issue and possibly fix it.
Thanks.

**Comment by Baggypants** [comment]
I can record the raw serial data from the serial port if that helps?

**Comment by falkTX** [comment]
yes. any data that you can provide will help

**Comment by Baggypants** [comment]
Here is a dump file. serial data on the left and timestamp on the right

https://gitlab.com/Baggypants/serial2jack/blob/513c86f6cb8165234c84fafc8533964293d6bcc2/dumpout

This is the python code used to generate it

https://gitlab.com/Baggypants/serial2jack/blob/513c86f6cb8165234c84fafc8533964293d6bcc2/dumpmid.py

the keyboard has Active Sensing on. I only played a C key  octave below middle c. initially on and off slowly, to get full midi messages, then quickly to show running status.

**Comment by interym** [comment]
has this been fixed on the zynthian system? im facing the same problem?

**Comment by falkTX** [comment]
> im facing the same problem?
is that a question or affirmation?

**Comment by interym** [comment]
second

**Comment by interym** [comment]
but from what date is the fix. maybe ive not made an update ever since

**Comment by falkTX** [comment]
Please update and retry, you should be using the latest version anyway.
Thanks
