### ISSUE TITLE
D50 hickup

### ISSUE THREAD

**Issue by mheidt** [moddevices/mod-ttymidi#8]
Hi,

I am using a D50 as master and since  using the latest commit, i get hickups.
Although only playing a trill between 59 and 60, other values are shown:
CH#00 NOTE_ON 60, Vel: 74
CH#00 NOTE_OFF 60, Vel: 64
CH#00 CONTROL_CHANGE 123 => 0
CH#00 NOTE_OFF 59, Vel: 64
CH#00 NOTE_ON **69,** Vel: 59
CH#00 NOTE_OFF **123**, Vel: 64
CH#00 NOTE_ON 60, Vel: 78
CH#00 NOTE_OFF 60, Vel: 64
CH#00 CONTROL_CHANGE 123 => 0
CH#00 NOTE_ON 59, Vel: 67
CH#00 NOTE_OFF 59, Vel: 64

Everything works fine, when I revert back to 
commit 028ce4e537c7c1a6c237f90c3747cf1794d2d843

But with the second commit of Jakob (first doesn't compile) the first issues occur. Just hanging notes.
And since the latest commit with the running status change, i get the picture above.

[d50_hickup.zip](https://github.com/moddevices/mod-ttymidi/files/3913652/d50_hickup.zip)

**Comment by falkTX** [comment]
This is very interesting.
Can you run in "print only" mode and see if that reads the garbage values?
(assuming you know the midi spec a little, otherwise it will be pointless)

**Comment by mheidt** [comment]
what is the print only mode?

**Comment by falkTX** [comment]
One of the CLI arguments for ttymidi. it prints the messages on the serial.
It is to find out if the issue is reading the serial line (so the decoding is fine), or if the problem is the decoding into MIDI.

**Comment by mheidt** [comment]
90	3c	52	90	3b	3a	3c	0	3b	0	b0	7b	0	90	3c	4c	3c	0	b0	7b	090	3b	3e	3b	0	b0	7b	0	90	3c	52	3c	0	b0	7b	0	90	3b	42	3b	0b0	7b	0	90	3c	4e	3c	0	b0	7b	090	3b	42	3b	0	b0	7b	0	90	3c	4c	90	3c	0	b0	7b	0	90	3b	42	90	3b	0	b0	7b	0	90	3c	36	3c	0b0	7b	0	90	3b	3f	3c	42	3b	0	90	3b	3e	3c	0	3c	45	90	3b	0	3c	0	b0	7b	0	90	3b	40	3b	0	b0	7b	0	90	3c	3e	3c	0	b0	7b	090	3b	3e	90	3c	44	3b	0	90	3c	0b0	7b	0	90	3b	41	3b	0	b0	7b	090	3c	46	3c	0	b0	7b	0	90	3b	42	3b	0	b0	7b	0	90	3c	41	90	3c	0	b0	7b	0	90	3b	42	90	3b	0b0	7b	0	90	3c	43	3c	0	b0	7b	090	3b	42	3b	0	b0	7b	0	90	3c	44	3c	0	b0	7b	0	90	3b	42	90	3c	48	3b	0	90	3c	0	b0	7b	0	90	3b	3e	3b	0	b0	7b	0	90	3c	42	3c	0	b0	7b	0	90	3b	42	90	3c	3e	3b	0	90	3c	0	b0	7b	0	90	3b	40	3c	42	3b	0	3c	0	b0	7b	0	90	3b	42	3c	43	3b	0	90	3c	0	b0	7b	0	90	3b	3e	90	3c	46	3b	0	3c	0	b0	7b	0	90	3b	42	3c	49	3b	0	90	3c	0	b0	7b	090	3b	3f	90	3c	47	3b	0	3c	0	b0	7b	0	90	3b	40	3c	4a	3b	0	3c	0	b0	7b	0	90	3b	42	90	3c	48	3b	0	90	3c	0	b0	7b	0	90	3b	40	3c	41	3b	0	3c	0	b0	7b	090	3b	3e	3c	45	90	3b	0	3c	0	b0	7b	0	90	3b	42	3c	3c	3b	0	3c	0	b0	7b	0	90	3b	3e	3c	52	3b	0	90	3c	0	b0	7b	0

**Comment by jofemodo** [comment]
@falkTX , I'm reading the code, trying to solve this issue and have a doubt ...

Why replacing note-on with velocity 0 by note-off? Note on with velocity 0 is perfectly OK with the MIDI specifications. The MIDI Specification says:

"A receiver must be capable of recognizing either method of turning off a note, and should treat them identically."

Thanks

**Comment by falkTX** [comment]
the no 0-velocity note-on is just for convenience, since it is not allowed in LV2.
See http://lv2plug.in/ns/ext/midi/midi.html#MidiEvent
> Note On messages with velocity 0 are not allowed. These messages are equivalent to Note Off in standard MIDI streams, but here only proper Note Off messages are allowed

Also after investigating jackd "seq" driver, I noticed that it also does the same thing (convert 0-velocity note-ons to note-offs), so it made sense to do the conversion early on.

If it is really something you want to see, do a pull request with a compiler macro.

**Comment by jofemodo** [comment]
OK! Understanded! I don't see any problem with it ... only curiosity ;-)

**Comment by jofemodo** [comment]
Hi @mheidt !

>missing delimiter whitespace as cause?

No, it's a copy/paste problem ;-)

**Comment by jofemodo** [comment]
I couldn't find any problem in the code ... 
We should compare the serial data dump with the MIDI events generated. A kind of "print" mode. For doing so, minor modifications are needed.

I've a modified version at:

>https://github.com/zynthian/mod-ttymidi

Please, test with it (you don't need to use the printonly" options) and send the dump in parallel to the MIDI log, so we can compare and see where the problem is.

Thanks!

**Comment by mheidt** [comment]
[d50-midi.log](https://github.com/moddevices/mod-ttymidi/files/3928943/d50-midi.log)
[raw.txt](https://github.com/moddevices/mod-ttymidi/files/3928945/raw.txt)

**Comment by mheidt** [comment]
be aware, that the pitchwheel messages in d50-midi are added by zynthian.

in the raw file I see
90	3b	0	39	
90	3b	0	b0	7b	0	
90	3c	0	42	3c	0	b0	7b	0	

I cannot explain the 39
and the 42 seems to be the wrong 
CH#01 NOTE_ON 66, Vel: 60

**Comment by mheidt** [comment]
Here is a log that is ok from the pre-Jakob code.
[raw_ok.txt](https://github.com/moddevices/mod-ttymidi/files/3936544/raw_ok.txt)
I guess, I need prints that are earlier and debug Jakobs code.

**Comment by mheidt** [comment]
I have a fix.
There was that mystery, that -printonly didn't show the hickups, but normal mode did.
The problem were the later reads with data_bytes_cnt.
When you loop and read the bits one by one with a fflush in each iteration, it works.
If @jofemodo opens his fork for me, I could push.
I changed the #ifdef DEBUG and used arguments.verbose instead.
@falkTX, or don't you want any verbose code in there to keep it faster?

**Comment by jofemodo** [comment]
@mheidt, you have write access now ;-)

**Comment by jofemodo** [comment]
Regarding the "verbose" flagged code inside the core, i think  we must keep "clean" the production code. This code is critical and executes with RT priority. Although latency will not be affected, we don't want to waste CPU cycles here.
Anyway, adding conditional debug code is always OK, at less until we have located and solved the problem ;-)

**Comment by mheidt** [comment]
We are going to test the fix in the zynthian community, before we request a PR.

**Comment by mheidt** [comment]
Please let me know, when you fixed the makefile issue.
